name: Windows Build Tests

on: [pull_request, workflow_dispatch]

jobs:
  windows-build:
      name: "Windows-Build"
      runs-on: windows-latest
      steps:
          - uses: actions/checkout@v4
          
          - name: Installing Choco
            shell: pwsh
            run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

          - name: Install tooling with Choco
            shell: pwsh
            run: |
                choco install cmake.install --version=3.31.6
                cmake --version
                choco install llvm --version=20.1.4
                clang++ --version
                choco install git make mingw
          
          - name: Pip installing conan
            shell: pwsh
            run: pip install conan
          
          - name: Setting up conan profiles
            shell: pwsh
            run: conan config install -sf profiles/x86_64/Windows/ -tf profiles https://github.com/engine3d-dev/conan-config.git
          
          - name: Setting up packages
            shell: pwsh
            run: conan remote add engine3d-conan https://libhal.jfrog.io/artifactory/api/conan/engine3d-conan
          
          - name: Running Test Cases
            shell: pwsh
            run: conan build . -b missing
